version: "3.9"
services:
  manager:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
    networks:
      network1:
        aliases:
          - manager

networks:
  network1:
    name: mynet