FROM mysql:8.0-debian
COPY ./broker/deploy.sh /docker-entrypoint-initdb.d
COPY . /bkr
WORKDIR /bkr

RUN apt-get update
RUN apt-get install -y python3
RUN apt-get install -y python3-pip

RUN pip install --upgrade pip
RUN pip install -r requirements.txt

ENV MYSQL_ROOT_PASSWORD="abc"

EXPOSE 5000