version: "3.9"
services:
  manager:
    build: ./manager
    image: manager
    container_name: manager
    ports:
      - "5000:5000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
    networks:
      network1:
        aliases:
          - manager
    environment:
      PERSIST: ${PERSISTENCE_MODE}

  manager2:
    build: ./manager2
    image: manager2
    container_name: manager2
    depends_on:
      - manager
    ports:
      - "5001:5000"
    networks:
      network1:
        aliases:
          - manager2

  broker:
    build: ./broker
    image: broker
    container_name: broker0
    networks:
      network1:
        aliases:
          - broker0
    environment:
      PERSIST: ${PERSISTENCE_MODE}
      BID: broker0

networks:
  network1:
    name: mynet